eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: service-registry-deployment.default.svc.cluster.local:8761/eureka/
  instance:
    hostname: service-registry-deployment

