eureka:
  instance:
    preferIpAddress: true
    hostname: 4.157.237.25
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://4.157.237.25:8761/eureka
